default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:
    - main
    - <?php echo sfConfig::get('app_site_theme') ?>/style

  javascripts:    
    - behavior
    - rating
    - reflection

  has_layout:     on
  layout:         layout
